f = open(".host",'r')
name = f.read()
print(name)
f.close()
f = open('main.cf','r')
txt = f.read()
f.close()
f = open('main.cf','w')
txt = txt.replace('brass',name)
f.write(txt)
f.close()
f = open('dovecot.conf','r')
txt = f.read()
f.close()
f = open('dovecot.conf','w')
txt = txt.replace('studio',name)
f.write(txt)
f.close()
